yarnPath: .yarn/releases/yarn-3.2.3.cjs
packageExtensions:
  react-grid-layout@*:
    peerDependencies:
      react-draggable: "4.4.5"
  react-resizable@*:
    peerDependencies:
      react-draggable: "4.4.5"
